"""
Civic Force Module
------------------

This module represents the operational arm of the Cerebrus Engine.
The Civic Force is responsible for executing tasks generated by:

- Ecology alerts
- Justice incidents
- Anti-capture signals
- Logistics anomalies
- Community requests

The module assigns members to tasks based on skills, availability,
and proximity. It also supports urgent interventions triggered by
high-risk events.

This is a simplified version of what a real civic operations system
would look like.
"""

from dataclasses import dataclass
from typing import List, Dict, Any, Optional


# ---------------------------------------------------------
# Data Models
# ---------------------------------------------------------

@dataclass
class CivicForceMember:
    """Represents a member of the Civic Force."""
    id: str
    name: str
    skills: List[str]
    location: str
    available: bool = True
    on_mission: bool = False


@dataclass
class CivicTask:
    """Represents a task assigned to the Civic Force."""
    id: str
    type: str  # e.g., "ecology_inspection", "justice_support", "urgent_intervention"
    priority: int  # 1 = low, 2 = medium, 3 = high
    required_skills: List[str]
    location: str
    assigned_member: Optional[str] = None
    completed: bool = False


# ---------------------------------------------------------
# Civic Force Module
# ---------------------------------------------------------

class CivicForceModule:
    """
    Core Civic Force module.

    Handles:
    - Task creation
    - Member-task matching
    - Urgent interventions
    - Task completion
    """

    def __init__(self):
        # Demo members
        self.members: List[CivicForceMember] = [
            CivicForceMember(id="CF-01", name="Ana Torres", skills=["ecology", "inspection"], location="Block A"),
            CivicForceMember(id="CF-02", name="Rui Mendes", skills=["security", "justice"], location="Block B"),
            CivicForceMember(id="CF-03", name="Sara Lima", skills=["logistics", "mobility"], location="Block C"),
        ]

        self.tasks: List[CivicTask] = []

    # -----------------------------------------------------
    # Task Creation
    # -----------------------------------------------------

    def create_task(self, task_type: str, priority: int, required_skills: List[str], location: str) -> CivicTask:
        """
        Creates a new civic task and stores it in the task list.
        """

        task = CivicTask(
            id=f"TASK-{len(self.tasks) + 1}",
            type=task_type,
            priority=priority,
            required_skills=required_skills,
            location=location
        )

        self.tasks.append(task)
        return task

    def create_urgent_task(self, description: str, location: str) -> CivicTask:
        """
        Creates a high-priority urgent task.
        """

        return self.create_task(
            task_type=f"urgent_intervention:{description}",
            priority=3,
            required_skills=["security"],
            location=location
        )

    # -----------------------------------------------------
    # Member Matching
    # -----------------------------------------------------

    def member_matches_task(self, member: CivicForceMember, task: CivicTask) -> bool:
        """Checks if a member has the required skills for a task."""
        return all(skill in member.skills for skill in task.required_skills)

    def score_member_for_task(self, member: CivicForceMember, task: CivicTask) -> int:
        """
        Computes a simple score for matching:
        +10 for each matching skill
        +5 if in the same block
        """
        score = 0

        for skill in task.required_skills:
            if skill in member.skills:
                score += 10

        if member.location == task.location:
            score += 5

        return score

    def assign_tasks(self) -> List[Dict[str, Any]]:
        """
        Assigns available members to unassigned tasks.

        Returns:
            list of assignment results.
        """

        results = []

        for task in self.tasks:
            if task.assigned_member or task.completed:
                continue

            # Find best matching member
            candidates = [
                m for m in self.members
                if m.available and not m.on_mission and self.member_matches_task(m, task)
            ]

            if not candidates:
                results.append({
                    "task_id": task.id,
                    "assigned": False,
                    "reason": "No available members with required skills."
                })
                continue

            # Score candidates
            best_member = max(candidates, key=lambda m: self.score_member_for_task(m, task))

            # Assign
            best_member.available = False
            best_member.on_mission = True
            task.assigned_member = best_member.id

            results.append({
                "task_id": task.id,
                "assigned": True,
                "member_id": best_member.id,
                "member_name": best_member.name
            })

        return results

    # -----------------------------------------------------
    # Task Completion
    # -----------------------------------------------------

    def complete_task(self, task_id: str) -> Dict[str, Any]:
        """
        Marks a task as completed and frees the assigned member.
        """

        for task in self.tasks:
            if task.id == task_id:
                task.completed = True

                if task.assigned_member:
                    member = next((m for m in self.members if m.id == task.assigned_member), None)
                    if member:
                        member.available = True
                        member.on_mission = False

                return {
                    "task_id": task_id,
                    "completed": True
                }

        return {
            "task_id": task_id,
            "completed": False,
            "error": "Task not found."
        }

    # -----------------------------------------------------
    # High-Level Intervention
    # -----------------------------------------------------

    def civic_force_intervention(self, description: str, location: str) -> Dict[str, Any]:
        """
        Creates an urgent task and immediately attempts assignment.
        """

        task = self.create_urgent_task(description, location)
        assignment_results = self.assign_tasks()

        return {
            "task": task,
            "assignment_results": assignment_results
        }
